### ISSUE TITLE
Charging session stopping at precharging stage

### ISSUE THREAD

**Issue by ganeshldsema** [Sevenstax/FreeV2G#10]
Hi,

I am trying Codico WB-CARRIER-BOARD-EI board for ISO15118 charging. RIght now I'm using FreeV2G python demo app from sevenstax.
I observed that the application stops at the pre-charge stage and does not send some required information to start the charging.
Could you please have a look on to the logs? (Bothe command line and serial port logs are attached.)
Firmware used in the board is Sevenstax_WHITEBEET_ISO15118_EVSE_SW_V01_01_02 (as updated in codico documentation area ).
[codico_commandline_log_003.txt](https://github.com/Sevenstax/FreeV2G/files/7334787/codico_commandline_log_003.txt)
[codico_serial_debug_log_003.txt](https://github.com/Sevenstax/FreeV2G/files/7334788/codico_serial_debug_log_003.txt)

-Ganesh LD

**Comment by ganeshldsema** [comment]
Here is the Wireshark log

**Comment by ganeshldsema** [comment]
Hi Vasily,

Here is the wireshark capture log.
Please rename the file extension to ".pcapng" before you open it with wireshark.

[codico_board_wireshark_log_003_pcapng_.txt](https://github.com/Sevenstax/FreeV2G/files/7370237/codico_board_wireshark_log_003_pcapng_.txt)

**Comment by ganeshldsema** [comment]
Hi..

Were you able to look into the issue?

**Comment by ttu-stx** [comment]
We will look into it within this week and come back to you.
BR

**Comment by ganeshldsema** [comment]
Hello Jan,

Any updates on this issue?

Thanks!

**Comment by vbudko** [comment]
Hi Ganesh,
We will place an update of the SW v01.01.03 today on the [](https://downloads.codico.com/misc/plc)
I will inform you with a separate email once it is done. 
BR, Vasily

**Comment by jpo-stx** [comment]
> 
> 
> Hello Jan,
> 
> Looks like that Codico board (EVSE) is not populating the charging schedules properly, (as per logs by simulator). All the 3 charging schedules are coming as "0" in the simulator side. Please refer to the logs.
> 
> -Ganesh
> 
> [codico_commandline_dc_003.txt](https://github.com/Sevenstax/FreeV2G/files/7431785/codico_commandline_dc_003.txt) [codico_serial_dc_003.txt](https://github.com/Sevenstax/FreeV2G/files/7431787/codico_serial_dc_003.txt) [trialog_dc__ev-combocs-log_001.txt](https://github.com/Sevenstax/FreeV2G/files/7431792/trialog_dc__ev-combocs-log_001.txt)

Hi @ganeshldsema ,
we have reworked the schedule handling, please check the updated user manual, which will also be available this week.

**Comment by jpo-stx** [comment]
@ganeshldsema , please check out the latest firmware version and user manual available for the Whitebeet.
With this I checked the schedules received on the EV:

```
ChargeParameterDiscoveryRes:
  Session ID: 07E0B6D14103DBAF
  ResponseCode: OK
  EVSEProcessing: Finished
  DC_EVSEChargeParameter:
    DC_EVSEStatus:
      EVSEIsolationStatus: Valid
      EVSEStatusCode: EVSE_Ready
      NotificationMaxDelay: 0
      EVSENotification: None
    EVSEMaximumCurrentLimit: 100e+0 A
    EVSEMaximumPowerLimit: 25000e+0 W
    EVSEMaximumVoltageLimit: 400e+0 V
    EVSEMinimumCurrentLimit: 0e+0 A
    EVSEMinimumVoltageLimit: 0e+0 V
    EVSEPeakCurrentRipple: 2e+0 A
  SAScheduleList:
    SAScheduleTuple #0:
      SAScheduleTupleID: 1
      PMaxSchedule:
        PMaxScheduleEntry #0:
          TimeInterval:
            start: 0
            duration: 1800
          EVMaximumPowerLimit: 25000e+0 W
        PMaxScheduleEntry #1:
          TimeInterval:
            start: 1800
            duration: 1800
          EVMaximumPowerLimit: 18750e+0 W
        PMaxScheduleEntry #2:
          TimeInterval:
            start: 3600
            duration: 82800
          EVMaximumPowerLimit: 12500e+0 W
```
